// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JobListing struct {
	ID          string `json:"id"`
	Company     string `json:"company"`
	Title       string `json:"title"`
	Website     string `json:"website"`
	ListingLink string `json:"listingLink"`
}
